name: Publish
on:
  push:
    branches:    
      - main

env:
  PUSHER_TOKEN: ${{ secrets.PUSHER_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
  
    # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
    steps:
      - name: Install Build Essential
        run: sudo apt install -y build-essential

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ env.PUSHER_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUSHER_NAME: nawibot
        run: |
          npm config set access public
          git config --global user.email nawibot@nosebit.com
          git config --global user.name nawibot
          yarn lerna run build
          yarn lerna publish --yes